---
- hosts: slave
  become: yes
  tasks:
    - name: Disable SELinux
      selinux:  
        state: disabled
        
    - name: Disable Firewalld 
      systemd:
        name: firewalld
        state: stopped
        enabled: false
       
    - name: Tuned Disable and Stop
      systemd:
        name: tuned
        state: stopped
        enabled: false


    - name: Rebooting
      reboot:
