---
- hosts: client
  vars:
    db_user: postgre
    db_name: trafikveri
    db_password:

  tasks:

    - name: "Ensure the PostgreSQL service is running"
      service: name=postgresql state=started enabled=yes
    - name: "Create app database"
      postgresql_db:
        state: present
        name: "{{ db_name }}"
      become: yes
      become_user: postgres

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: yes
      become_user: postgres

    - name: "Ensure user has access to the new database"
      become: yes
      become_user: postgres
      postgresql_user: db={{ db_name }}
        name={{ db_user }}
        password={{ db_password }}
        priv=ALL
        state=present 

    - name: "Ensure user does not have unnecessary permission"
      become: yes
      become_user: postgres
      postgresql_user: name={{ db_user }}
           role_attr_flags=NOSUPERUSER,NOCREATEDB
           state=present

